<?php
// reports/export_excel.php — Export sales report as Excel CSV
$adminOnly = true;
require_once '../includes/auth_guard.php';
require_once '../config/db.php';

$dateFrom = $_GET['date_from'] ?? date('Y-m-01');
$dateTo   = $_GET['date_to']   ?? date('Y-m-d');

// Set headers for Excel download
$filename = 'BigVybes_Sales_' . $dateFrom . '_to_' . $dateTo . '.csv';
header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Pragma: no-cache');
header('Expires: 0');

$output = fopen('php://output', 'w');

// ─── Sheet 1: Summary ─────────────────────────────────────────────────────────
$stmt = $conn->prepare("SELECT COUNT(*) as total_txns, SUM(total_amount) as total_revenue FROM sales WHERE DATE(date) BETWEEN ? AND ?");
$stmt->bind_param("ss", $dateFrom, $dateTo);
$stmt->execute();
$summary = $stmt->get_result()->fetch_assoc();
$stmt->close();

fputcsv($output, ['BIGVYBES SUPERMARKET - SALES REPORT']);
fputcsv($output, ['Period:', $dateFrom . ' to ' . $dateTo]);
fputcsv($output, ['Generated:', date('d M Y h:i A')]);
fputcsv($output, ['Generated By:', $_SESSION['username']]);
fputcsv($output, []);

fputcsv($output, ['=== SUMMARY ===']);
fputcsv($output, ['Total Revenue', 'GH₵ ' . number_format($summary['total_revenue'] ?? 0, 2)]);
fputcsv($output, ['Total Transactions', $summary['total_txns'] ?? 0]);
fputcsv($output, ['Average Sale Value', 'GH₵ ' . ($summary['total_txns'] > 0 ? number_format($summary['total_revenue'] / $summary['total_txns'], 2) : '0.00')]);
fputcsv($output, []);

// ─── Payment Breakdown ────────────────────────────────────────────────────────
$stmt = $conn->prepare("SELECT payment_method, COUNT(*) as count, SUM(total_amount) as total FROM sales WHERE DATE(date) BETWEEN ? AND ? GROUP BY payment_method");
$stmt->bind_param("ss", $dateFrom, $dateTo);
$stmt->execute();
$paymentBreakdown = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
$stmt->close();

fputcsv($output, ['=== PAYMENT METHOD BREAKDOWN ===']);
fputcsv($output, ['Method', 'Transactions', 'Total Revenue']);
foreach ($paymentBreakdown as $p) {
    fputcsv($output, [strtoupper($p['payment_method']), $p['count'], 'GH₵ ' . number_format($p['total'], 2)]);
}
fputcsv($output, []);

// ─── Top Products ─────────────────────────────────────────────────────────────
$stmt = $conn->prepare("SELECT p.name, SUM(si.quantity) as total_sold, SUM(si.quantity * si.price) as revenue
                         FROM sale_items si JOIN products p ON si.product_id = p.id
                         JOIN sales s ON si.sale_id = s.id
                         WHERE DATE(s.date) BETWEEN ? AND ?
                         GROUP BY p.id ORDER BY total_sold DESC LIMIT 10");
$stmt->bind_param("ss", $dateFrom, $dateTo);
$stmt->execute();
$topProducts = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
$stmt->close();

fputcsv($output, ['=== TOP SELLING PRODUCTS ===']);
fputcsv($output, ['#', 'Product Name', 'Units Sold', 'Revenue']);
foreach ($topProducts as $i => $p) {
    fputcsv($output, [$i + 1, $p['name'], $p['total_sold'], 'GH₵ ' . number_format($p['revenue'], 2)]);
}
fputcsv($output, []);

// ─── Transaction History ──────────────────────────────────────────────────────
$stmt = $conn->prepare("SELECT s.id, s.total_amount, s.date, s.payment_method, s.payment_reference, u.username as cashier
                         FROM sales s JOIN users u ON s.cashier_id = u.id
                         WHERE DATE(s.date) BETWEEN ? AND ?
                         ORDER BY s.date DESC");
$stmt->bind_param("ss", $dateFrom, $dateTo);
$stmt->execute();
$transactions = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
$stmt->close();

fputcsv($output, ['=== TRANSACTION HISTORY ===']);
fputcsv($output, ['Sale #', 'Date', 'Time', 'Cashier', 'Payment Method', 'Reference', 'Amount (GH₵)']);
foreach ($transactions as $t) {
    fputcsv($output, [
        '#' . $t['id'],
        date('d M Y', strtotime($t['date'])),
        date('h:i A', strtotime($t['date'])),
        $t['cashier'],
        strtoupper($t['payment_method']),
        $t['payment_reference'] ?? '',
        number_format($t['total_amount'], 2)
    ]);
}

fclose($output);
exit;
